# Generated by Django 5.0.4 on 2024-05-08 14:11

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vehicle_num0", models.CharField(max_length=10)),
                ("vehicle_num", models.CharField(max_length=10)),
                ("driver", models.CharField(blank=True, max_length=50, null=True)),
                ("maker", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "vehicle_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("passenger_num", models.PositiveIntegerField(blank=True, null=True)),
                ("type", models.CharField(blank=True, max_length=50, null=True)),
                ("model_year", models.PositiveIntegerField(blank=True, null=True)),
                ("vehicle_id", models.CharField(max_length=50, unique=True)),
                ("release_date", models.DateField(blank=True, null=True)),
                ("check_date", models.DateField(blank=True, null=True)),
                ("motor_type", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "rated_output",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "vehicle_registration",
                    models.FileField(blank=True, null=True, upload_to="vehicles/"),
                ),
            ],
        ),
    ]
